import Head from "next/head";
import Footer from "../components/footer";
import Header from "../components/header";
import { Col, Container, Row, ToastContainer } from "react-bootstrap";
import firebaseApp from "firebase/app";
import { db } from "<cgch-ch>/config/firebaseConfig";

import React, { useEffect, useState } from 'react'


function About() {
  const [aboutUsState, setAboutUsState] = useState('')
  // Fetch data on component mount
  useEffect(() => {
    firebaseApp
    .auth()
    .signInAnonymously()
    .then(() => {
      fetchData();
    })
    .catch((error) => {
      firebaseApp
        .auth()
        .signInAnonymously()
        .then(() => {
          fetchData();
        })
        .catch((error) => {
          if (error.code === "auth/operation-not-allowed") {
          }
        });
      if (error.code === "auth/operation-not-allowed") {
      }
    });
  }, []); // Empty dependency array to run effect only on mount
async function fetchData() {
  try {
    db.collection("Seo_section")
      .doc('About-us-About us')
      .get()
      .then((docSnapshot) => {
        console.log("document ", docSnapshot);
        if (docSnapshot.exists) {
          setAboutUsState(docSnapshot.data())
          
        } else {
          console.log("No such document!");
        }
      })
      .catch((error) => {
        console.error('Error fetching document:', error);
      });
  } catch (error) {
    console.error('Error in try-catch:', error);
  }
}
  return (
    <div>
             {aboutUsState && aboutUsState.seo &&(
           <Head>
        {/* General Meta Tags */}
        <title>{aboutUsState.seo.seo_title}</title>
        <meta name="description" content={aboutUsState.seo.seo_description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {/* Open Graph Meta Tags (for Facebook, LinkedIn, etc.) */}
        <meta property="og:title" content={aboutUsState.seo.og_title} />
        <meta property="og:description" content={aboutUsState.seo.og_description} />
        <meta property="og:image" content="https://chennaigatedcommunity.in/home%20loan.svg" />
        <meta property="og:url" content={aboutUsState.seo.og_url} />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="chennai gated community" />

        {/* Twitter Meta Tags */}
        <meta name="twitter:title" content="Projects - Your Website Name" />
        <meta name="twitter:description" content="cgc homes best property portal is the fastest growing real estate portal, you can buy flat, new flats, resale flats, duplex flats and sell residential property for best price" />
        <meta name="twitter:image" content="https://chennaigatedcommunity.in/home%20loan.svg" />
      </Head>
      )}
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/style.css"/>
      </Head>
      <Header/>
      <Container>
        <Row className="mt-5 mb-5">
          <Col>
          <p>CGC Homes is co-founded and managed by,</p>
          <p>Ravishankar, Mechanical Engineer from College of Engineering, Guindy, Chennai with 13 years of sales and operations experience in the fields of Office Automation, IT, Engineering and Telecom. Has been associated with brands like Canon, Tata and Airtel.</p>
          <p>Joy, MS in IT and Management with 14 years of sales and operations experience in the fields of Healthcare and Telecom. Has been associated with brands like Tata, Dishnet DSL, Airtel and Sigma Laboratories.</p>
          </Col>
        </Row>
       
        </Container>
      <Footer/>
    </div>
  );
}

export default About;
